### ISSUE TITLE
Bug cBoxAresta

### ISSUE THREAD

**Issue by ldarabas** [programmerGM/TrabalhoFaculdadeGrafos#2]
Quando insere arestas e depois seta elas nos nós e volta a editar o campo de arestas, a lista reseta e é possível inserir os mesmos nós novamente, aí vai acumulando na lista, não removendo os antigos

**Comment by mauriciogeneroso** [comment]
As matrizes estavam sendo reiniciadas porém as listas não. Ajustado para que as listas reiniciem também.
