### ISSUE TITLE
Atalho Ctrl + H

### ISSUE THREAD

**Issue by mauriciogeneroso** [programmerGM/TrabalhoFaculdadeGrafos#5]
Atalho não está abrindo a janela Sobre.

**Comment by ldarabas** [comment]
Control + H é um bug do java, atalho trocado para Control + Q.
Agora funciona.

**Comment by ldarabas** [comment]
Mais informações 
http://stackoverflow.com/questions/19333053/jmenubar-hide-jmenu-with-shortcut-ctrlh-keystroke-dont-work-after-setvisibl
