### ISSUE TITLE
Botão grafo conexo não funciona

### ISSUE THREAD

**Issue by ldarabas** [programmerGM/TrabalhoFaculdadeGrafos#6]
Não traz nenhuma mensagem, nem erro.

**Comment by mauriciogeneroso** [comment]
O erro ta ocorrendo porque acessa uma posição inválida do vetor criado no próprio método para verificar se é conexo ou não.
Linha 159: "vetor[vetorsomado] = n;"

**Comment by mauriciogeneroso** [comment]
Tem que ser analisado o próprio algoritmo o que signifca a contagem do "vetorsomado".
Obs: vamos analisar com o Luiz e o Gustavo que estão fazendo o algoritmo.

**Comment by mauriciogeneroso** [comment]
https://github.com/programmerGM/TrabalhoFaculdadeGrafos/commit/75fce5a7a093d83d646a653e1751a65d3023e909
